### ISSUE TITLE
can't navigate away from /Edit/:id 

### ISSUE THREAD

**Issue by coryjquirk** [coryjquirk/cart-croc#59]
can't navigate away from /Edit/:id  using the Navbar. gives you paths like /Edit/:id/home or /Edit/:id/checkout

**Comment by coryjquirk** [comment]
![image](https://user-images.githubusercontent.com/68253966/101562085-46258200-398c-11eb-990d-b1c6151ff43b.png)

**Comment by josh8903** [comment]
Added '/' before routes on navbar component to fix
